spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/malldb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: "root"
    password: "root1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 86400
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true
logging:
  level:
    sql: trace
